# Generated by Django 5.2.5 on 2025-08-08 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('reminder_time', models.DateTimeField(default=datetime.datetime(2025, 8, 8, 8, 35, 5, 563621))),
            ],
        ),
    ]
