# Generated by Django 5.2.5 on 2025-08-08 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='image',
            field=models.FileField(blank=True, upload_to='tasks_images'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='reminder_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 8, 16, 28, 59, 215981)),
        ),
    ]
