# Generated by Django 5.2.5 on 2025-08-26 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_image_alter_tasks_reminder_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=23)),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='reminder_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 26, 8, 19, 52, 272360)),
        ),
    ]
