# Generated by Django 5.2.5 on 2025-08-28 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_profile_alter_tasks_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='reminder_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 6, 7, 41, 685887)),
        ),
    ]
