# Generated by Django 5.2.5 on 2025-08-28 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasks_priority_alter_tasks_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='new_priority',
            field=models.CharField(blank=True, choices=[('low', 'LOW'), ('high', 'HIGH'), ('medium', 'MEDIUM')]),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='reminder_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 8, 20, 44, 559119)),
        ),
    ]
