# Generated by Django 5.2.5 on 2025-08-28 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '006_tasks_users_migration_to_new_priorities'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(default='not_done', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='reminder_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 15, 2, 1, 543102)),
        ),
    ]
