# Generated by Django 5.2.5 on 2025-08-28 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tasks_status_alter_tasks_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='new_status',
            field=models.CharField(blank=True, choices=[('completed', 'COMPLETED'), ('pending', 'PENDING')]),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='reminder_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 15, 3, 39, 656658)),
        ),
    ]
