# Generated by Django 5.2.5 on 2025-08-28 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '009_tasks_users_migration_to_new_priorities copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='reminder_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 15, 6, 54, 422779)),
        ),
    ]
