name: CI Pipeline

on:
  push:
    branches: [ "feature/devops_lite" ]
  pull_request:
    branches: [ "feature/devops_lite" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        echo "No tests yet, but this is where tests would run!"

    - name: Build Docker image
      run: docker build -t hello-docker .


  # deploy:
  #   depends_on: build

  #   steps:
  #   - name: Log in to Docker Hub
  #     uses: docker/login-action@v2
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}

  #   - name: Push image
  #     run: |
  #       docker tag devops_lite ${{ secrets.DOCKER_USERNAME }}/devops_lite:latest
  #       docker push ${{ secrets.DOCKER_USERNAME }}/devops_lite:latest
